[package]
name = "terminal-ai-ops"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.23.2"
bytes = "1.6.0"
color-eyre = "0.6.3"
crossterm = "0.27.0"
futures = "0.3.30"
portable-pty = "0.8.1"
ratatui = "0.26.3"
tokio = { version = "1.38.0", features = ["full"] }
tui-term = "0.1.11"
vt100 = "0.15.2"
